server.port=8087

apitester.base-package=com.apitester.example.controller
apitester.output-dir=resources/collection.json
apitester.parent-folder=Management
apitester.server.url=http://localhost:8087
apitester.format=json
apitester.include-headers=Authorization,Content-Type
apitester.timeout=5000
apitester.generate-env-file=true
